config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, except: :index do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    # @movie = Movie.find(params[:movie_id])
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    # @bookmark.movie = @movie
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy

    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:edit, :update, :show, :destroy]

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def index
    @lists = List.all
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<br>
<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit list", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner"
     style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
     url(https://entrepreneurship.babson.edu/wp-content/uploads/2020/10/Movie-1200-630.jpg);">
  <div class="container">
    <h1>Here are your lists of movies!</h1>
    <%= link_to "Add a list", new_list_path, class: "btn btn-flat" %>
  </div>
</div>
<div class="container">
  <div class="cards">
    <% @lists.each do |list| %>
      <div class="card-category"
           style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
           url("<%= cl_image_path list.photo.key, object_fit: :contain %>")'>
        <%= link_to list.name, list_path(list) %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= simple_form_for [ @list ] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key %>);">
  <div class="container">
    <h1><%= @list.name %></h1>
    <%= link_to "Return to Lists", root_path, class: "btn btn-flat" %>
    <%= link_to "Add a new bookmark", new_list_bookmark_path(@list), class: "btn btn-flat" %>
  </div>
</div>


<div class="container">
  <div class="cards">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card-trip">
          <img src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %>-poster">
        <div class="card-trip-infos">
          <div>
            <h2><%= bookmark.movie.title %></h2>
            <h3><%= bookmark.movie.rating %> ★</h3>
          </div>
          <p><%= bookmark.movie.overview %></p>
          <br>
          <p><em>"<%= bookmark.comment %>"</em></p>
          <%= link_to "Delete",
                    bookmark_path(bookmark),
                    method: :delete,
                    class: "btn btn-ghost",
                    data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%=  %>